packages:
  # all packages in direct subdirs of packages/
  - 'slides/*'
allowBuilds:
  esbuild: true
  fsevents: true
  playwright-chromium: true
  workerd: true
minimumReleaseAgeExclude:
  - miniflare@5.20260730.0-alpha
  - wrangler@4.117.0
